### PR TITLE
feat: upgrade frontend platform to version 3

### PR DESCRIPTION
**Pull request by leangseu-edx**
BREAKING CHANGE:
- No longer support `@edx/frontend-platform@^2.0.0`

### CODE REVIEW

**Review by arbrandes — CHANGES_REQUESTED** [review]
No objections (this component doesn't use caching explicitly), but can you please rebase on master and regenerate package-lock?

**Comment by leangseu-edx** [comment]
Update requested change

**Review by arbrandes — APPROVED** [review]
Looks good, thanks!

**Comment by adamstankiewicz** [comment]
@arbrandes @leangseu-edx Just a heads up, this PR could have been released as a non-breaking change if the peer dependency range denoted compatibility with v2 **and** v3 of `@edx/frontend-platform` (e.g., `^2.0.0 || ^3.0.0`), which is true since this component doesn't use caching explicitly as @arbrandes identified earlier 😄 

@leangseu-edx Also, reminder... if we make a change in this repository that is a breaking change for the component API or peer dependencies, an equivalent change should be made in our `-footer-edx` equivalent repository.

**Comment by adamstankiewicz** [comment]
@leangseu-edx @arbrandes Also note, the PR description denoted this as a breaking change (which it was) but it wasn't actually released to NPM as a breaking change...

**Comment by arbrandes** [comment]
@adamstankiewicz, any idea what the commit message missed?  I was under the impression only a `BREAKING CHANGE:` in the body would be enough.  Do we normally also need an exclamation point after the tag?  (`feat!:`)?

**Comment by adamstankiewicz** [comment]
@arbrandes `BREAKING CHANGE:` in the body should be all it requires, however, I don't think the [commit](https://github.com/openedx/frontend-component-footer/commit/159b5a842ebd5154790996a96e68ce0aea1d92b8) that merged with `master` included the `BREAKING CHANGE:` in the commit body (it's only in the PR description).

**Pull request merged**
