### PR TITLE
chore(i18n): add more languages

### PR DESCRIPTION
**Pull request by Yoiber071**
Add Transifex Working Group languages.

New language codes: it_IT,pt_PT,de_DE

@feanil 
@natabene

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Yoiber071!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by e0d** [comment]
@mphilbrick211 tests run.

**Comment by e0d** [comment]
@Yoiber071 looks like there are test failures.

**Comment by Yoiber071** [comment]
Hi, Sorry for the late response, I've fixed the lint failures, and is ready to be tested again.

**Comment by e0d** [comment]
@Yoiber071 We will merge changes back from master as part of the review process, however, we need authors to handle conflicts.  Can you have a look?

**Comment by mphilbrick211** [comment]
@openedx/arch-bom would someone mind reviewing and merging if all looks good?

**Comment by jmbowman** [comment]
Redirecting to @openedx/fed-bom , as they maintain this repo now.

**Pull request merged**
