### PR TITLE
Upgrade frontend-build to v12

### PR DESCRIPTION
**Pull request by BilalQamar95**
**Ticket:**
[42: Upgrade eslint to v8.x](https://github.com/openedx/frontend-wg/issues/42)

**What changed?**
- Updated `frontend-build `to v12 (Eslint was updated in `frontend-build` version resulting in it's version being bumped to v12. This PR updates `frontend-build` to reciprocate eslint version update)
- Resolved `eslint` issues post update

### CODE REVIEW

**Comment by Mashal-m** [comment]
working fine, ready to review.
@abdullahwaheed

**Review by arbrandes — APPROVED** [review]
Looks good to me! +1

**Comment by arbrandes** [comment]
@BilalQamar95, is this still valid?  If so, we need to resolve the package-lock conflict.

**Comment by BilalQamar95** [comment]
> @BilalQamar95, is this still valid? If so, we need to resolve the package-lock conflict.

Yes this is still valid, I have resolved the package-lock conflict

**Pull request merged**
